# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  shoulder_pan_joint:
    max_position: 2.8
    min_position: -5.0
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 3.15
  shoulder_lift_joint:
    max_position: 0.2
    min_position: -3.0
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 3.15
  elbow_joint:
    max_position: 3.0
    min_position: -1.0
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 3.15
  wrist_1_joint:
    max_position: 2.2
    min_position: -3.2
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 3.2
  wrist_2_joint:
    max_position: 3.7
    min_position: -1.4
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 3.2
  wrist_3_joint:
    max_position: 5.4
    min_position: -2.4
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 3.2
  index_proximal_joint:
    max_position: 1.47
    min_position: 0.0
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  middle_proximal_joint:
    max_position: 1.47
    min_position: 0.0
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  pinky_proximal_joint:
    max_position: 1.47
    min_position: 0.0
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  ring_proximal_joint:
    max_position: 1.47
    min_position: 0.0
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  thumb_proximal_pitch_joint:
    max_position: 1.308
    min_position: 0.0
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  thumb_proximal_yaw_joint:
    max_position: 0.6
    min_position: 0.0
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0